### ISSUE TITLE
Range of Krippendorff Alpha

### ISSUE THREAD

**Issue by createmomo** [vinid/quica#4]
Hi,

this is not an issue of the tool. I would like to seek your opinion about the question: do you have any idea what is the range of the Krippendorff alpha?

I google-searched this question, however, I found the answers online was quite different. Some posts said it was between -1 and 1. Some were saying it is between 0 and 1. And someone just says it is from negative to 1.

Thank you very much~

**Comment by vinid** [comment]
Hello! 

If I remember well Krippendorff's alpha should be in [0, 1]
